language: java

jdk:
    - openjdk8

before_script:
    - wget "https://releases.hashicorp.com/consul/1.0.6/consul_1.0.6_linux_amd64.zip"
    - unzip "consul_1.0.6_linux_amd64.zip"
    - ./consul agent --dev&

script:
    - mvn compile
    - curl "http://127.0.0.1:8500/v1/kv/test/db.default.driver" -d "org.postgresql.Driver" -X PUT
    - curl "http://127.0.0.1:8500/v1/kv/test/db/default/timeout" -d "5000" -X PUT
    - curl "http://127.0.0.1:8500/v1/kv/test/db/default/excludedIds" -d "[1,2,3,4,5]" -X PUT
    - curl "http://127.0.0.1:8500/v1/kv/test/db/default/disabled" -d "false" -X PUT
    - curl "http://127.0.0.1:8500/v1/kv/my/key" -d "Hello World" -X PUT
    - curl "http://127.0.0.1:8500/v1/kv/file/test" -d "<FILE>./test;SGVsbG8gV29ybGQh" -X PUT
    - mvn test
